spring:
  profiles:
    active:
      - dev
---
server:
  port: 7004

spring:
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: eureka4.cn #eureka服务端的实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka
---
server:
  port: 7004

spring:
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: eureka4.cn #eureka服务端的实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka