spring:
  profiles:
    active:
      - dev
---
server:
  port: 7004

spring:
  profiles: dev
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: eureka4.cn #eureka服务端的实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
---
server:
  port: 7004

spring:
  profiles: test
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: eureka4.cn #eureka服务端的实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
