spring:
  profiles:
    active:
      - dev
---
server:
  port: 7004

spring:
  profiles: dev
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: eureka4.cn #eureka服务端的实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
---
server:
  port: 7004

spring:
  profiles: test
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: eureka4.cn #eureka服务端的实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
