spring:
  profiles:
    active:
      - dev
---
server:
  port: 7004

spring:
  profiles: dev
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    service-url:
      defaultZone: http://localhost:7004/eureka
---
server:
  port: 7004

spring:
  profiles: test
  application:
    name: avex-eureka

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    service-url:
      defaultZone: http://localhost:7004/eureka
